// Mocks generated by Mockito 5.4.4 from annotations
// in pro_image_editor/test/widgets/auto_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

// Flutter imports:
import 'package:flutter/material.dart' as _i5;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:pro_image_editor/models/editor_image.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EditorImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditorImage extends _i1.Mock implements _i2.EditorImage {
  @override
  set byteArray(_i3.Uint8List? _byteArray) => super.noSuchMethod(
        Invocation.setter(
          #byteArray,
          _byteArray,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasBytes => (super.noSuchMethod(
        Invocation.getter(#hasBytes),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasNetworkUrl => (super.noSuchMethod(
        Invocation.getter(#hasNetworkUrl),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasFile => (super.noSuchMethod(
        Invocation.getter(#hasFile),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAssetPath => (super.noSuchMethod(
        Invocation.getter(#hasAssetPath),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.EditorImageType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i2.EditorImageType.file,
        returnValueForMissingStub: _i2.EditorImageType.file,
      ) as _i2.EditorImageType);

  @override
  _i4.Future<_i3.Uint8List> safeByteArray(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeByteArray,
          [context],
        ),
        returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
      ) as _i4.Future<_i3.Uint8List>);
}
