{
  "format_version": 2,
  "sksl": {
    "entrypoint": "pixelate_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_size;\nuniform float u_pixel_block_size;\nuniform vec2 u_device_size;\nuniform float u_fit_to_width;\nuniform shader u_texture_input;\nuniform half2 u_texture_input_size;\n\nvec4 frag_color;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    float _28;\n    if (u_fit_to_width == 1.0)\n    {\n        _28 = u_size.x / u_device_size.x;\n    }\n    else\n    {\n        _28 = u_size.y / u_device_size.y;\n    }\n    float generationHelper = _28;\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / u_size;\n    float pixelBlockSize = u_pixel_block_size * generationHelper;\n    vec2 pixelated_uv = (floor((uv * u_size) / vec2(pixelBlockSize)) * pixelBlockSize) / u_size;\n    frag_color = u_texture_input.eval(u_texture_input_size * ( pixelated_uv));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return frag_color;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_pixel_block_size",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_device_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "u_fit_to_width",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "u_texture_input",
        "rows": 1,
        "type": 12
      }
    ]
  }
}